In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [141]:
df = pd.read_csv('new_york_sample_1km.csv')

In [142]:
df.columns = ['uid', 't', 'd', 'x', 'y']
df

uid   t     d    x   y
0           67  17  13.0  653  39
1           67  19  13.0  640  26
2           67  20  13.0  640  26
3           67  39  13.0  641  27
4           67   0  14.0  644  30
...        ...  ..   ...  ...  ..
69343  2647547  23  19.0  613   3
69344  2647547   1  20.0  631  10
69345  2647547  16  20.0  631  20
69346  2647547  21  20.0  640  36
69347  2647547  22  20.0  638  28

[69348 rows x 5 columns]

In [143]:
df.max()

uid    2647547.0
t           45.0
d           20.0
x          877.0
y          681.0
dtype: float64

In [144]:
df["d"].unique()

array([13., 14., 15., 16., 17., 18., 19., 20.,  1.,  2.,  3.,  4.,  5.,
        6.,  7.,  8.,  9., 10., 11., 12.])

In [145]:
print(df['x'].max())
print(df['y'].max())
print(df['t'].max())
print(df['d'].max())

877
681
45
20.0


In [146]:
users_in_train = int(df['uid'].nunique()*0.8)
users_in_test = df['uid'].nunique() - users_in_train

users_list_train = df['uid'].unique()[:users_in_train]
users_list_test = df['uid'].unique()[users_in_train:]

In [147]:
train = df[df["uid"].isin(users_list_train)]
test = df[df["uid"].isin(users_list_test)]

In [148]:
train = train.astype(dtype = {'uid': 'int64', 't': 'int64', 'd': 'int64', 'x': 'int64', 'y': 'int64'})
test = test.astype(dtype = {'uid': 'int64', 't': 'int64', 'd': 'int64', 'x': 'int64', 'y': 'int64'})

In [149]:
train.sort_values(['uid', 'd', 't'], ascending=True).to_csv("train.csv", index=False)
test.sort_values(['uid', 'd', 't'], ascending=True).to_csv("test.csv", index=False)
# train.to_csv("train.csv", index=False)

In [71]:
sorted(train['d'].unique())

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [33]:
test_data = test.sort_values(['uid', 'd', 't'], ascending=True)
test_data = test[test['d']<=10]
test_validation = test[test['d']>10]
test_data.to_csv("test.csv", index=False)
test_validation.to_csv("validation.csv", index=False)

In [72]:
d_unique = np.unique(train['d'])
d_unique[(d_unique >= np.min(d_unique)) & (d_unique <= np.max(d_unique) - 5)]

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
mask_d_start = np.random.choice(d_unique[(d_unique >= np.min(d_unique)) & (d_unique <= np.max(d_unique) - 5)])
mask_d_end = mask_d_start + 4
need_mask_idx = np.where((train['d'] >= mask_d_start) & (train['d'] <= mask_d_end))

In [74]:
print(mask_d_start, mask_d_end)

6 10


In [75]:
need_mask_idx

(array([   2,    3,    4, ..., 5612, 5613, 5614]),)

In [3]:
pd.read_csv('train.csv').d.max()

14

In [7]:
pd.read_csv('test.csv').d

0        15
1        15
2        16
3        16
4        16
         ..
43572    16
43573    17
43574    17
43575    18
43576    18
Name: d, Length: 43577, dtype: int64